---------------------------- MODULE behavior ----------------------------
\* TLA+ Behavior Specification
\* Generated by spec-driven plugin
\*
\* This file contains behavioral assertions:
\* - State variables
\* - Initial state predicate
\* - Actions (state transitions)
\* - Safety invariants
\* - Liveness properties
\* - Fairness conditions

EXTENDS Integers, Sequences, FiniteSets

\*===========================================================================
\* STATE VARIABLES
\* Define the state space of your system
\*===========================================================================

\* Example:
\* VARIABLES state, balance, transactions

\*===========================================================================
\* TYPE INVARIANT
\* Defines valid states (checked at every step)
\*===========================================================================

\* TypeOK ==
\*     /\ state \in {"idle", "processing", "done"}
\*     /\ balance \in Int
\*     /\ transactions \in Seq([type: {"deposit", "withdraw"}, amount: Nat])

\*===========================================================================
\* INITIAL STATE
\*===========================================================================

\* Init ==
\*     /\ state = "idle"
\*     /\ balance = 0
\*     /\ transactions = <<>>

\*===========================================================================
\* ACTIONS
\* Define state transitions
\*===========================================================================

\* Example: Deposit action
\* Deposit(amount) ==
\*     /\ amount > 0
\*     /\ balance' = balance + amount
\*     /\ transactions' = Append(transactions, [type |-> "deposit", amount |-> amount])
\*     /\ UNCHANGED state

\* Example: Withdraw action
\* Withdraw(amount) ==
\*     /\ amount > 0
\*     /\ amount <= balance
\*     /\ balance' = balance - amount
\*     /\ transactions' = Append(transactions, [type |-> "withdraw", amount |-> amount])
\*     /\ UNCHANGED state

\*===========================================================================
\* NEXT STATE RELATION
\* Combines all possible actions
\*===========================================================================

\* Next ==
\*     \/ \E a \in 1..100: Deposit(a)
\*     \/ \E a \in 1..100: Withdraw(a)

\*===========================================================================
\* SAFETY PROPERTIES
\* Things that must always be true
\*===========================================================================

\* Example: Balance never negative
\* BalanceNonNegative == balance >= 0

\* Example: No double processing
\* NoDoubleProcessing == \* define based on your domain

\*===========================================================================
\* LIVENESS PROPERTIES
\* Things that must eventually happen
\*===========================================================================

\* Example: Requests eventually complete
\* RequestCompletion == Request ~> Response

\*===========================================================================
\* FAIRNESS CONDITIONS
\* Ensure progress (no infinite stuttering)
\*===========================================================================

\* Fairness == WF_<<state, balance, transactions>>(Next)

\*===========================================================================
\* SPECIFICATION
\* Combines Init, Next, and Fairness
\*===========================================================================

\* vars == <<state, balance, transactions>>
\* Spec == Init /\ [][Next]_vars /\ Fairness

\*===========================================================================
\* ADD YOUR SPECIFICATIONS BELOW
\*===========================================================================

==========================================================================
